<template>
  <v-data-table
    :headers="headers"
    :items="cards"
    :items-per-page="5"
    class="elevation-1"
  ></v-data-table>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class CollectionTable extends Vue {
  headers: undefined;
  cards: undefined;

  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
  data() {
    return {
      headers: [
        { text: 'No.', value: 'number' },
        { text: 'Name', value: 'name' },
        { text: 'Type', value: 'type' },
        { text: 'Rarity', value: 'rarity' },
        { text: 'Artist', value: 'artist' },
        { text: 'Price', value: 'price' },
        { text: 'Number in Collection', value: 'numberInCollection' },
      ],
      cards: [
        {
          number: '1',
          name: '+2 Mace',
          type: 'Artifact — Equipment',
          rarity: 'common',
          artist: 'Jarel Threat',
          price: '$0.03',
          numberInCollection: 3,
        },
        {
          number: '2',
          name: 'Arborea Pegasus',
          type: 'Creature',
          rarity: 'common',
          artist: 'Justyna Gil',
          price: '$0.03',
          numberInCollection: 2,
        },
        {
          number: '3',
          name: 'Blink Dog',
          type: 'Creature',
          rarity: 'Uncommon',
          artist: 'Oriana Menendez',
          price: '$0.07',
          numberInCollection: 1,
        },
        {
          number: 1,
          name: 'velit eu est',
          type: 'duis',
          rarity: 'duis',
          artist: 'Carie McKew',
          price: '$7.56',
          numberInCollection: 4,
        },
        {
          number: 2,
          name: 'ultrices',
          type: 'nec nisi',
          rarity: 'id',
          artist: 'Dexter McNab',
          price: '$7.54',
          numberInCollection: 4,
        },
        {
          number: 3,
          name: 'fermentum donec ut',
          type: 'ridiculus',
          rarity: 'nec',
          artist: 'Sheilah Fills',
          price: '$0.12',
          numberInCollection: 9,
        },
        {
          number: 4,
          name: 'convallis tortor risus',
          type: 'dignissim',
          rarity: 'orci',
          artist: 'Christin Thorneloe',
          price: '$0.21',
          numberInCollection: 7,
        },
        {
          number: 5,
          name: 'at',
          type: 'amet',
          rarity: 'hac',
          artist: 'Brenn Challener',
          price: '$2.25',
          numberInCollection: 9,
        },
        {
          number: 6,
          name: 'interdum venenatis turpis',
          type: 'primis',
          rarity: 'elementum',
          artist: 'Caren Lowin',
          price: '$9.17',
          numberInCollection: 10,
        },
        {
          number: 7,
          name: 'semper interdum',
          type: 'libero',
          rarity: 'congue',
          artist: 'Sal Cordeau',
          price: '$2.68',
          numberInCollection: 2,
        },
        {
          number: 8,
          name: 'est lacinia nisi',
          type: 'non velit',
          rarity: 'eros',
          artist: 'Harald Bernardoux',
          price: '$4.25',
          numberInCollection: 3,
        },
        {
          number: 9,
          name: 'id sapien',
          type: 'mus etiam',
          rarity: 'vehicula',
          artist: 'Sharron Kirkpatrick',
          price: '$8.65',
          numberInCollection: 7,
        },
        {
          number: 10,
          name: 'felis ut at',
          type: 'tincidunt eget',
          rarity: 'ultrices',
          artist: 'Regen Jorger',
          price: '$1.14',
          numberInCollection: 4,
        },
        {
          number: 11,
          name: 'quam fringilla',
          type: 'vel',
          rarity: 'vestibulum',
          artist: 'Cate Whimpenny',
          price: '$6.28',
          numberInCollection: 2,
        },
        {
          number: 12,
          name: 'eros viverra',
          type: 'sed nisl',
          rarity: 'felis',
          artist: 'Bonni Stennine',
          price: '$5.38',
          numberInCollection: 10,
        },
        {
          number: 13,
          name: 'pellentesque ultrices mattis',
          type: 'felis donec',
          rarity: 'eget',
          artist: 'Dacy McMeekin',
          price: '$2.81',
          numberInCollection: 2,
        },
        {
          number: 14,
          name: 'condimentum curabitur in',
          type: 'auctor sed',
          rarity: 'libero',
          artist: 'Ofella Chudleigh',
          price: '$7.18',
          numberInCollection: 6,
        },
        {
          number: 15,
          name: 'orci luctus et',
          type: 'non',
          rarity: 'id',
          artist: 'Ragnar Sewell',
          price: '$8.53',
          numberInCollection: 8,
        },
        {
          number: 16,
          name: 'lacus at velit',
          type: 'elementum ligula',
          rarity: 'euismod',
          artist: 'Cullie Wrixon',
          price: '$3.90',
          numberInCollection: 10,
        },
        {
          number: 17,
          name: 'accumsan odio',
          type: 'ut nunc',
          rarity: 'eget',
          artist: 'Tiffy Bertolin',
          price: '$5.90',
          numberInCollection: 2,
        },
        {
          number: 18,
          name: 'ultricies',
          type: 'eget',
          rarity: 'sed',
          artist: 'Josi Cremins',
          price: '$4.50',
          numberInCollection: 1,
        },
        {
          number: 19,
          name: 'suscipit a feugiat',
          type: 'luctus',
          rarity: 'libero',
          artist: 'Genna Tomkiss',
          price: '$6.09',
          numberInCollection: 1,
        },
        {
          number: 20,
          name: 'sed lacus',
          type: 'libero',
          rarity: 'convallis',
          artist: 'Arturo Gilogly',
          price: '$3.86',
          numberInCollection: 6,
        },
        {
          number: 21,
          name: 'ante ipsum primis',
          type: 'orci luctus',
          rarity: 'justo',
          artist: 'Blakeley Toppes',
          price: '$5.93',
          numberInCollection: 7,
        },
        {
          number: 22,
          name: 'dolor',
          type: 'justo',
          rarity: 'magna',
          artist: 'Arnoldo Meekings',
          price: '$5.36',
          numberInCollection: 6,
        },
        {
          number: 23,
          name: 'hac habitasse',
          type: 'ut erat',
          rarity: 'sapien',
          artist: 'Ashly Poter',
          price: '$3.77',
          numberInCollection: 6,
        },
        {
          number: 24,
          name: 'in',
          type: 'erat',
          rarity: 'iaculis',
          artist: 'Isadore Slayford',
          price: '$6.32',
          numberInCollection: 4,
        },
        {
          number: 25,
          name: 'at feugiat',
          type: 'praesent',
          rarity: 'dolor',
          artist: 'Arnold Allden',
          price: '$6.74',
          numberInCollection: 6,
        },
        {
          number: 26,
          name: 'vulputate justo in',
          type: 'rutrum ac',
          rarity: 'in',
          artist: 'Ryley McMurtyr',
          price: '$7.94',
          numberInCollection: 8,
        },
        {
          number: 27,
          name: 'integer',
          type: 'dolor morbi',
          rarity: 'eros',
          artist: 'Rogers Cortes',
          price: '$8.02',
          numberInCollection: 4,
        },
        {
          number: 28,
          name: 'a nibh',
          type: 'sit',
          rarity: 'nulla',
          artist: 'Vassily Gottschalk',
          price: '$6.56',
          numberInCollection: 10,
        },
        {
          number: 29,
          name: 'pede posuere',
          type: 'suscipit',
          rarity: 'proin',
          artist: 'Tristan Waye',
          price: '$7.14',
          numberInCollection: 8,
        },
        {
          number: 30,
          name: 'nunc',
          type: 'dis parturient',
          rarity: 'erat',
          artist: 'Wainwright Tancock',
          price: '$2.86',
          numberInCollection: 1,
        },
        {
          number: 31,
          name: 'libero',
          type: 'eu felis',
          rarity: 'suscipit',
          artist: 'Barron Silby',
          price: '$5.06',
          numberInCollection: 4,
        },
        {
          number: 32,
          name: 'integer pede',
          type: 'mauris laoreet',
          rarity: 'phasellus',
          artist: 'Riki Girvan',
          price: '$8.68',
          numberInCollection: 8,
        },
        {
          number: 33,
          name: 'vel lectus in',
          type: 'cursus',
          rarity: 'cubilia',
          artist: 'Jolie English',
          price: '$0.51',
          numberInCollection: 8,
        },
        {
          number: 34,
          name: 'elit',
          type: 'mauris',
          rarity: 'cubilia',
          artist: 'Adiana Zollner',
          price: '$6.34',
          numberInCollection: 3,
        },
        {
          number: 35,
          name: 'sapien',
          type: 'in blandit',
          rarity: 'nullam',
          artist: 'Keene Davids',
          price: '$2.25',
          numberInCollection: 2,
        },
        {
          number: 36,
          name: 'nunc nisl duis',
          type: 'morbi ut',
          rarity: 'in',
          artist: 'Ursola Hanvey',
          price: '$2.26',
          numberInCollection: 8,
        },
        {
          number: 37,
          name: 'mauris laoreet ut',
          type: 'justo',
          rarity: 'in',
          artist: 'Kalvin Hourstan',
          price: '$9.75',
          numberInCollection: 10,
        },
        {
          number: 38,
          name: 'vel augue vestibulum',
          type: 'mi pede',
          rarity: 'blandit',
          artist: 'Nerita Phethean',
          price: '$5.98',
          numberInCollection: 4,
        },
        {
          number: 39,
          name: 'sed sagittis nam',
          type: 'integer ac',
          rarity: 'libero',
          artist: 'Tobi Khomich',
          price: '$6.27',
          numberInCollection: 7,
        },
        {
          number: 40,
          name: 'turpis donec',
          type: 'erat fermentum',
          rarity: 'luctus',
          artist: 'Elane Olander',
          price: '$5.03',
          numberInCollection: 5,
        },
        {
          number: 41,
          name: 'mattis',
          type: 'tristique fusce',
          rarity: 'risus',
          artist: 'Jacki Belhomme',
          price: '$7.69',
          numberInCollection: 9,
        },
        {
          number: 42,
          name: 'et ultrices posuere',
          type: 'vulputate',
          rarity: 'arcu',
          artist: 'Rex Tiptaft',
          price: '$0.46',
          numberInCollection: 2,
        },
        {
          number: 43,
          name: 'non lectus aliquam',
          type: 'felis eu',
          rarity: 'etiam',
          artist: 'Wilone Mattusevich',
          price: '$2.77',
          numberInCollection: 4,
        },
        {
          number: 44,
          name: 'vulputate nonummy',
          type: 'ut suscipit',
          rarity: 'luctus',
          artist: 'Waiter McDirmid',
          price: '$7.50',
          numberInCollection: 6,
        },
        {
          number: 45,
          name: 'faucibus orci luctus',
          type: 'dapibus augue',
          rarity: 'ut',
          artist: 'Jennette Olenin',
          price: '$1.65',
          numberInCollection: 6,
        },
        {
          number: 46,
          name: 'at nibh',
          type: 'proin',
          rarity: 'amet',
          artist: 'Patrizia Ismead',
          price: '$4.66',
          numberInCollection: 7,
        },
        {
          number: 47,
          name: 'et commodo',
          type: 'ut',
          rarity: 'in',
          artist: 'Bernetta Chetwynd',
          price: '$9.85',
          numberInCollection: 10,
        },
        {
          number: 48,
          name: 'neque',
          type: 'est',
          rarity: 'interdum',
          artist: 'Cy Cawsy',
          price: '$0.99',
          numberInCollection: 9,
        },
        {
          number: 49,
          name: 'non',
          type: 'proin eu',
          rarity: 'ut',
          artist: 'Keary Hiseman',
          price: '$0.00',
          numberInCollection: 7,
        },
        {
          number: 50,
          name: 'maecenas leo odio',
          type: 'habitasse platea',
          rarity: 'justo',
          artist: 'Corinna Robbs',
          price: '$6.09',
          numberInCollection: 4,
        },
        {
          number: 51,
          name: 'vestibulum',
          type: 'nulla',
          rarity: 'quam',
          artist: 'Sadella Bigley',
          price: '$1.86',
          numberInCollection: 7,
        },
        {
          number: 52,
          name: 'vestibulum vestibulum ante',
          type: 'blandit',
          rarity: 'felis',
          artist: 'Bentlee Kendall',
          price: '$1.09',
          numberInCollection: 7,
        },
        {
          number: 53,
          name: 'interdum eu tincidunt',
          type: 'libero non',
          rarity: 'imperdiet',
          artist: 'Stinky Benit',
          price: '$8.15',
          numberInCollection: 2,
        },
        {
          number: 54,
          name: 'etiam faucibus',
          type: 'sed vel',
          rarity: 'lectus',
          artist: 'Illa Kencott',
          price: '$5.80',
          numberInCollection: 7,
        },
        {
          number: 55,
          name: 'id ornare',
          type: 'nunc',
          rarity: 'dolor',
          artist: 'Valentin Tremberth',
          price: '$2.55',
          numberInCollection: 5,
        },
        {
          number: 56,
          name: 'nunc',
          type: 'ultrices',
          rarity: 'arcu',
          artist: 'Von Cypler',
          price: '$4.11',
          numberInCollection: 2,
        },
        {
          number: 57,
          name: 'aliquam augue quam',
          type: 'porttitor',
          rarity: 'amet',
          artist: 'Reba Assiter',
          price: '$3.70',
          numberInCollection: 10,
        },
        {
          number: 58,
          name: 'odio curabitur',
          type: 'potenti',
          rarity: 'congue',
          artist: 'Tomlin Nore',
          price: '$8.65',
          numberInCollection: 5,
        },
        {
          number: 59,
          name: 'lacus',
          type: 'interdum eu',
          rarity: 'nam',
          artist: 'Prudi Hulburt',
          price: '$6.65',
          numberInCollection: 7,
        },
        {
          number: 60,
          name: 'massa volutpat convallis',
          type: 'vulputate elementum',
          rarity: 'erat',
          artist: 'Vick Trench',
          price: '$8.00',
          numberInCollection: 10,
        },
        {
          number: 61,
          name: 'porttitor lorem',
          type: 'sed tristique',
          rarity: 'at',
          artist: 'Pieter Doole',
          price: '$9.59',
          numberInCollection: 3,
        },
        {
          number: 62,
          name: 'leo',
          type: 'rutrum neque',
          rarity: 'metus',
          artist: 'Mignonne McLean',
          price: '$6.17',
          numberInCollection: 2,
        },
        {
          number: 63,
          name: 'ac est',
          type: 'non',
          rarity: 'nibh',
          artist: 'Ruggiero Gummory',
          price: '$5.70',
          numberInCollection: 9,
        },
        {
          number: 64,
          name: 'quam turpis adipiscing',
          type: 'duis faucibus',
          rarity: 'condimentum',
          artist: 'Carlos Foreman',
          price: '$0.58',
          numberInCollection: 6,
        },
        {
          number: 65,
          name: 'nulla nunc',
          type: 'luctus tincidunt',
          rarity: 'semper',
          artist: 'Marilyn Janacek',
          price: '$6.89',
          numberInCollection: 1,
        },
        {
          number: 66,
          name: 'quisque erat eros',
          type: 'massa volutpat',
          rarity: 'dui',
          artist: 'Franni Satterfitt',
          price: '$4.61',
          numberInCollection: 3,
        },
        {
          number: 67,
          name: 'massa quis',
          type: 'justo pellentesque',
          rarity: 'pede',
          artist: 'Caresa Coster',
          price: '$2.03',
          numberInCollection: 3,
        },
        {
          number: 68,
          name: 'pellentesque at',
          type: 'mollis',
          rarity: 'quisque',
          artist: 'Tommie Ivey',
          price: '$8.34',
          numberInCollection: 10,
        },
        {
          number: 69,
          name: 'curabitur',
          type: 'morbi non',
          rarity: 'auctor',
          artist: 'Analise Rottenbury',
          price: '$6.94',
          numberInCollection: 3,
        },
        {
          number: 70,
          name: 'augue luctus tincidunt',
          type: 'diam',
          rarity: 'cras',
          artist: 'Bat Mitchenson',
          price: '$5.66',
          numberInCollection: 9,
        },
        {
          number: 71,
          name: 'sagittis nam congue',
          type: 'id',
          rarity: 'nulla',
          artist: 'Troy Leglise',
          price: '$5.61',
          numberInCollection: 6,
        },
        {
          number: 72,
          name: 'mattis odio donec',
          type: 'consequat dui',
          rarity: 'orci',
          artist: 'Nikita Aloshkin',
          price: '$4.80',
          numberInCollection: 4,
        },
        {
          number: 73,
          name: 'eu felis',
          type: 'faucibus',
          rarity: 'justo',
          artist: 'Gwendolen Steggles',
          price: '$3.38',
          numberInCollection: 4,
        },
        {
          number: 74,
          name: 'lorem integer tincidunt',
          type: 'sed tincidunt',
          rarity: 'ornare',
          artist: 'Vincenz Stiff',
          price: '$1.82',
          numberInCollection: 5,
        },
        {
          number: 75,
          name: 'nascetur ridiculus mus',
          type: 'venenatis',
          rarity: 'mauris',
          artist: 'Kennie Remer',
          price: '$9.76',
          numberInCollection: 10,
        },
        {
          number: 76,
          name: 'est phasellus sit',
          type: 'sed',
          rarity: 'montes',
          artist: 'Zollie Longford',
          price: '$7.70',
          numberInCollection: 5,
        },
        {
          number: 77,
          name: 'non velit nec',
          type: 'ut dolor',
          rarity: 'ut',
          artist: 'Gus Offener',
          price: '$8.90',
          numberInCollection: 8,
        },
        {
          number: 78,
          name: 'vel',
          type: 'nulla elit',
          rarity: 'vestibulum',
          artist: 'Gianna Sillars',
          price: '$4.96',
          numberInCollection: 7,
        },
        {
          number: 79,
          name: 'ipsum',
          type: 'quis turpis',
          rarity: 'luctus',
          artist: 'Rouvin Abbado',
          price: '$5.29',
          numberInCollection: 10,
        },
        {
          number: 80,
          name: 'volutpat',
          type: 'morbi',
          rarity: 'venenatis',
          artist: 'Merralee Goodbar',
          price: '$8.16',
          numberInCollection: 1,
        },
        {
          number: 81,
          name: 'ante ipsum',
          type: 'sapien',
          rarity: 'ut',
          artist: 'Bobbie Ryland',
          price: '$2.22',
          numberInCollection: 1,
        },
        {
          number: 82,
          name: 'ullamcorper purus',
          type: 'lacinia',
          rarity: 'posuere',
          artist: 'Rozina Drackford',
          price: '$7.73',
          numberInCollection: 3,
        },
        {
          number: 83,
          name: 'in',
          type: 'porttitor',
          rarity: 'in',
          artist: 'Rikki Sodeau',
          price: '$8.11',
          numberInCollection: 2,
        },
        {
          number: 84,
          name: 'purus sit',
          type: 'aliquam augue',
          rarity: 'iaculis',
          artist: 'Kathlin Faltskog',
          price: '$6.78',
          numberInCollection: 4,
        },
        {
          number: 85,
          name: 'eget tincidunt eget',
          type: 'suspendisse accumsan',
          rarity: 'neque',
          artist: 'Chaddie Philippault',
          price: '$8.63',
          numberInCollection: 6,
        },
        {
          number: 86,
          name: 'potenti nullam porttitor',
          type: 'justo pellentesque',
          rarity: 'turpis',
          artist: 'Simmonds MacRitchie',
          price: '$7.70',
          numberInCollection: 6,
        },
        {
          number: 87,
          name: 'id nisl',
          type: 'amet diam',
          rarity: 'nulla',
          artist: 'Ronnie Linsey',
          price: '$2.08',
          numberInCollection: 6,
        },
        {
          number: 88,
          name: 'porta volutpat quam',
          type: 'justo eu',
          rarity: 'mauris',
          artist: 'Carey Brumfield',
          price: '$9.86',
          numberInCollection: 3,
        },
        {
          number: 89,
          name: 'tincidunt',
          type: 'et',
          rarity: 'sed',
          artist: 'Sydel Klimkovich',
          price: '$1.26',
          numberInCollection: 3,
        },
        {
          number: 90,
          name: 'tincidunt ante vel',
          type: 'ante vivamus',
          rarity: 'faucibus',
          artist: 'Emmi Lob',
          price: '$1.55',
          numberInCollection: 1,
        },
        {
          number: 91,
          name: 'proin interdum mauris',
          type: 'bibendum felis',
          rarity: 'vitae',
          artist: 'Alessandra Terlinden',
          price: '$5.14',
          numberInCollection: 10,
        },
        {
          number: 92,
          name: 'semper rutrum nulla',
          type: 'ut suscipit',
          rarity: 'mauris',
          artist: 'Lyda Easterling',
          price: '$9.31',
          numberInCollection: 4,
        },
        {
          number: 93,
          name: 'tortor',
          type: 'morbi non',
          rarity: 'at',
          artist: 'Katina Peppett',
          price: '$2.25',
          numberInCollection: 9,
        },
        {
          number: 94,
          name: 'vel ipsum praesent',
          type: 'purus phasellus',
          rarity: 'accumsan',
          artist: 'Brandon Kinig',
          price: '$9.54',
          numberInCollection: 6,
        },
        {
          number: 95,
          name: 'diam',
          type: 'velit donec',
          rarity: 'rutrum',
          artist: 'Gwen Etridge',
          price: '$8.71',
          numberInCollection: 9,
        },
        {
          number: 96,
          name: 'erat fermentum justo',
          type: 'elit sodales',
          rarity: 'id',
          artist: 'Tyson McEnery',
          price: '$7.02',
          numberInCollection: 4,
        },
        {
          number: 97,
          name: 'integer tincidunt',
          type: 'sed accumsan',
          rarity: 'condimentum',
          artist: 'Lincoln Baitson',
          price: '$8.61',
          numberInCollection: 8,
        },
        {
          number: 98,
          name: 'orci',
          type: 'nec dui',
          rarity: 'nulla',
          artist: 'Johan Ackers',
          price: '$0.82',
          numberInCollection: 1,
        },
        {
          number: 99,
          name: 'etiam pretium',
          type: 'quis lectus',
          rarity: 'luctus',
          artist: 'Ernst Lanchbery',
          price: '$8.25',
          numberInCollection: 8,
        },
        {
          number: 100,
          name: 'integer tincidunt ante',
          type: 'nunc commodo',
          rarity: 'dolor',
          artist: 'Sheelah Lawrey',
          price: '$0.72',
          numberInCollection: 10,
        },
      ],
    };
  }
}
</script>
